### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Vilsol** [Vilsol/go-pob#6]
# THIS LIST IS INCOMPLETE

### General:
- [ ] Chrome has some elements not-in-dark theme e.g. the dropdowns when not hovered.
- [x] #17
- [x] Either use a consistent search algo when hovering nodes for pathing, or somehow provide options to choose to the user. #13

### Frontend:
- [ ] Frontend tests for all pages
- **Home**
  - [ ] Switch between games
  - [x] Build list
  - [x] Build folders
  - [x] Rename/move/manage
- **Import Export Build**
  - [ ] Character import from game
  - [ ] Build sharing
  - [ ] Import from URL
  - [x] Import from code
- **Notes**
  - [ ] Custom WYSIWYG Editor for notes with tiptap.
  - [ ] On build import, translate from old PoB format to new HTML-based.
- **Configuration**
  - [ ] Show only options that are relevant.
- **Tree**
  - [ ] Cluster Jewels
  - [ ] Stat differences on node allocation/deallocation
  - [ ] Multiple trees
  - [ ] Node power
  - [ ] Search/filter
  - [ ] Timeless Jewels
- **Skills**
  - [ ] Multiple skill sets
  - [ ] Copy/Paste
  - [ ] Gem Options
  - [ ] Full DPS
  - [ ] Socketed In
  - [ ] Stat differences on skill allocation/deallocation
- **Items**
  - [ ] Item Database
  - [ ] Players Items
  - [ ] Item Crafting
  - [ ] Custom Items
  - [ ] Weapon Sets
  - [ ] Item Sets
  - [ ] Cluster Jewels
- **Calcs**
  - [x] Render calculation table outputs
  - [ ] Separate skill selection
  - [ ] Implement all breakdowns
  - [ ] Hide unrelated tables

### Backend:
- [ ] All of the backend requirements for frontend
- [ ] Unit tests for a huge array of builds
- [x] Build storage/management
- [ ] Note translation from old PoB
- [ ] Implement config options
- [ ] Port existing Lua calculations (should expand into separate points)
- [ ] Spreadsheet engine
